main: main.cpp opt_alg.h matrix.h ode_solver.h solution.h user_funs.h
	g++ -c main -o main.cpp

matrix.o: matrix.cpp matrix.h
	g++ -c matrix.o -o matrix.cpp

ode_solver.o: ode_solver.cpp ode_solver.h
	g++ -c ode_solver.o -o ode_solver.cpp

opt_alg.o: opt_alg.cpp opt_alg.h
	g++ -c opt_alg.o -o opt_alg.cpp

solution.o: solution.cpp solution.h
	g++ -c solution.o -o solution.cpp

user_funs.o: user_funs.cpp user_funs.h
	g++ -c user_funs.o -o user_funs.cpp